webapp/main/urls.py
from django.conf.urls import patterns, url, include

from . import views

urlpatterns = patterns(
    '',
    url(r'^$',
        views.start,
        name='start'),
    url(r'^start/$',
        views.wishlist_start,
        name='wishlist_start'),
    url(r'^verify/(?P<identifier>\w{16})$',
        views.wishlist_verify,
        name='wishlist_verify'),
    url(r'^about/$',
        views.about,
        name='about'),
    url(r'^terms/$',
        views.terms,
        name='terms'),
    url(r'^help/$',
        views.help_page,
        name='help'),
    url(r'^rules/$',
        views.rules,
        name='rules'),
    url(r'^how-it-works/$',
        views.how_it_works,
        name='how_it_works'),
    url(r'^instructions/shipping-address/$',
        views.instructions_shipping_address,
        name='instructions_shipping_address'),
    url(r'^inboundemail/$',
        views.inbound_email,
        name='inbound_email'),
   url(r'^(?P<identifier>[a-f0-9]{8})/$',
        views.wishlist_home,
        name='wishlist'),
    url(r'^(?P<identifier>[a-f0-9]{8})/pick-one/$',
        views.wishlist_pick_one,
        name='wishlist_pick_one'),
    url(r'^(?P<identifier>[a-f0-9]{8})/pick-another/$',
        views.wishlist_pick_another,
        name='wishlist_pick_another'),
    url(r'^(?P<identifier>[a-f0-9]{8})/settings/$',
        views.wishlist_settings,
        name='wishlist_settings'),
    url(r'^(?P<identifier>[a-f0-9]{8})/close/$',
        views.close_item,
        name='close_item'),
    url(r'^(?P<identifier>[a-f0-9]{8})/your-name/$',
        views.wishlist_your_name,
        name='wishlist_your_name'),
    url(r'^(?P<identifier>[a-f0-9]{8})/your-message/$',
        views.wishlist_your_message,
        name='wishlist_your_message'),
    url(r'^(?P<identifier>[a-f0-9]{8})/already-set-up/$',
        views.wishlist_taken,
        name='wishlist_taken'),
    url(r'^(?P<identifier>[a-f0-9]{3,8})/$',
        views.wishlist_home,
        {'fuzzy': True},
        name='wishlist_fuzzy'),
    url(r'^(?P<identifier>[a-f0-9]{8})/share-by-email/$',
        views.wishlist_share_by_email,
        name='wishlist_share_by_email'),
    url(r'^find/$',
        views.find_wishlist,
        name='find_wishlist'),
    url(r'^debugger$',
        views.debugger,
        name='debugger'),

 )

webapp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.contrib import admin

#admin.autodiscover()

handler500 = 'webapp.main.views.handler500'


urlpatterns = patterns('',
#    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
#    url(r'^admin/', include(admin.site.urls)),
    url(r'^browserid/', include('django_browserid.urls')),
    url(r'^manage/', include('webapp.manage.urls', namespace='manage')),
    url(r'', include('webapp.main.urls', namespace='main')),
)


## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns(
        '',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    )
    urlpatterns += staticfiles_urlpatterns()

webapp/main/models.py
import decimal

from django.dispatch import receiver
from django.db import models
from django.db.models import Sum

from sorl.thumbnail import ImageField

from . import utils


class Wishlist(models.Model):
    identifier = models.CharField(max_length=8,
                                  default=utils.identifier_maker(8))
    amazon_id = models.CharField(max_length=20, db_index=True, unique=True)
    verified = models.DateTimeField(null=True)
    email = models.EmailField(null=True)
    name = models.CharField(max_length=100)
    mugshot = ImageField(upload_to=utils.upload_path('mugshot'))
    address = models.TextField(null=True)
    ship_to = models.TextField(null=True)
    public = models.BooleanField(default=False)
    unsubscribe_reminders = models.BooleanField(default=False)
    added = models.DateTimeField(default=utils.now)
    modified = models.DateTimeField(default=utils.now)

    def __str__(self):
        return self.identifier

    def __repr__(self):
        return (
            '<%s: %s (%s)>' % (
                self.__class__.__name__,
                self.identifier, self.amazon_id
            )
        )

    @property
    def verification_email_sent(self):
        return bool(Verification.objects.filter(wishlist=self))

    @property
    def name_or_email(self):
        return self.name or self.email

    def get_preferred_item(self):
        qs = (
            Item.objects
            .filter(wishlist=self, preference__gte=1)
            .order_by('preference', '-modified')
        )
        for item in qs[:1]:
            return item


class Item(models.Model):
    identifier = models.CharField(max_length=8,
                                  default=utils.identifier_maker(8))
    wishlist = models.ForeignKey(Wishlist)
    title = models.CharField(max_length=400)
    url = models.URLField(max_length=400)
    affiliates_url = models.URLField(max_length=400, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    picture = ImageField(upload_to=utils.upload_path('pictures'))
    preference = models.IntegerField(default=0)
    complete = models.BooleanField(default=False)
    fulfilled = models.BooleanField(default=False)
    fulfilled_notes = models.TextField(null=True)
    closed = models.BooleanField(default=False)
    closed_notes = models.TextField(null=True)
    cancelled = models.DateTimeField(null=True)
    congratulation_emailed = models.DateTimeField(null=True)
    amazon_api_converted = models.BooleanField(default=True)
    added = models.DateTimeField(default=utils.now)
    modified = models.DateTimeField(default=utils.now)

    def __str__(self):
        return self.title

    @property
    def amount_remaining(self):
        total = Payment.objects.filter(item=self).aggregate(Sum('amount'))
        if total['amount__sum']:
            total = total['amount__sum']
            return self.price - total
        else:
            return self.price

    @property
    def affiliates_url_or_url(self):
        if self.affiliates_url:
            return self.affiliates_url
        return self.url
        if '?' in url:
            url += '&'
        else:
            url += '?'
        url += 'tag=wislisgra-20'
        return url

    def get_progress(self):
        goal_amount = self.price
        sum_ = (
            Payment.objects
            .filter(item=self)
            .exclude(declined=True)
            .aggregate(Sum('amount'), Sum('refund_amount'))
        )
        amount = sum_['amount__sum'] or decimal.Decimal('0')
        amount -= sum_['refund_amount__sum'] or decimal.Decimal('0')
        percent = int(100 * float(amount / goal_amount))
        return amount, percent

    @property
    def progress_percent(self):
        return self.get_progress()[1]

    @property
    def progress_amount(self):
        return self.get_progress()[0]

    @property
    def amount_remaining(self):
        amount, __ = self.get_progress()
        return self.price - amount

    @property
    def views(self):
        pageviews = Pageviews.objects.filter(item=self).aggregate(Sum('views'))
        if pageviews:
            return pageviews['views__sum']
        return 0

    @property
    def has_payments(self):
        payments = self._finished_payments()
        return payments.exists()

    @property
    def days_left(self):
        payments = self._finished_payments()
        for payment in payments.order_by('added')[:1]:
            return 30 - (utils.now() - payment.added).days

    def _finished_payments(self):
        return (
            Payment.objects
            .filter(item=self, declined=False, refund_amount=decimal.Decimal('0.00'))
        )


class Payment(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    item = models.ForeignKey(Item)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    actual_amount = models.DecimalField(max_digits=5, decimal_places=2)
    hide_amount = models.BooleanField(default=False)
    email = models.EmailField(null=True)
    #hide_email = models.BooleanField(default=False)
    name = models.CharField(max_length=100, null=True)
    hide_name = models.BooleanField(default=False)
    message = models.TextField(null=True)
    hide_message = models.BooleanField(default=False)
    # this default was only necessary for South migrations
    balanced_uri = models.CharField(max_length=255, default='')
    balanced_hash = models.CharField(max_length=200, null=True)
    receipt_emailed = models.DateTimeField(null=True)
    notification_emailed = models.DateTimeField(null=True)
    refund_amount = models.DecimalField(max_digits=5, decimal_places=2,
                                        default=decimal.Decimal('0.00'))
    declined = models.BooleanField(default=False)
    added = models.DateTimeField(default=utils.now)
    modified = models.DateTimeField(default=utils.now)

    def __repr__(self):
        return (
            '<%s: $%.2f by %s on %s>' % (
                self.__class__.__name__,
                self.amount,
                self.email,
                self.item.identifier
            )
        )

    @property
    def actual_fee(self):
        return self.actual_amount - self.amount

    @property
    def balanced_marketplace_url(self):
        uri = self.balanced_uri
        uri = uri.replace('/v1', '')
        return (
            'https://dashboard.balancedpayments.com/#%s' % uri
        )


class Verification(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    email = models.EmailField()
    identifier = models.CharField(max_length=16,
                                  default=utils.identifier_maker(16))
    added = models.DateTimeField(default=utils.now)


class Pageviews(models.Model):
    item = models.ForeignKey(Item)
    views = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()

    added = models.DateTimeField(default=utils.now)
    modified = models.DateTimeField(default=utils.now)


class SentReminder(models.Model):
    item = models.ForeignKey(Item)
    body = models.TextField()
    to = models.EmailField()
    subject = models.TextField()
    added = models.DateTimeField(default=utils.now)
    modified = models.DateTimeField(default=utils.now)

    def __repr__(self):
        return '<%s: to:%s>' % (self.__class__.__name__, self.to)


class SplitExperiment(models.Model):
    slug = models.SlugField()
    template = models.CharField(max_length=100)
    success = models.IntegerField(default=0)
    #remote_addr = models.CharField(max_length=15)
    #user_agent = models.TextField()

    def __repr__(self):
        return '<%s: (%s, %s, %d)>' % (self.__class__.__name__, self.slug, self.template, self.success)


@receiver(models.signals.pre_save, sender=Wishlist)
@receiver(models.signals.pre_save, sender=Item)
@receiver(models.signals.pre_save, sender=Payment)
@receiver(models.signals.pre_save, sender=Pageviews)
@receiver(models.signals.pre_save, sender=SentReminder)
def update_modified(sender, instance, raw, *args, **kwargs):
    if raw:
        return
    instance.modified = utils.now()

webapp/main/forms.py
import re
import decimal

from django import forms
from flanker.addresslib import address

from . import models
from . import utils


WISHLIST_ID_REGEX = re.compile('^[0-9A-Z]{10,15}$')


class _BaseForm(object):
    def clean(self):
        cleaned_data = super(_BaseForm, self).clean()
        for field in cleaned_data:
            if isinstance(cleaned_data[field], basestring):
                cleaned_data[field] = (
                    cleaned_data[field].replace('\r\n', '\n')
                    .replace(u'\u2018', "'").replace(u'\u2019', "'").strip())

        return cleaned_data


class BaseModelForm(_BaseForm, forms.ModelForm):
    pass


class BaseForm(_BaseForm, forms.Form):
    pass


class WishlistIDForm(BaseForm):

    amazon_id = forms.CharField()

    def clean_amazon_id(self):
        value = self.cleaned_data['amazon_id']
        print "VALUE", repr(value)
        if '://' in value:
            value = utils.find_wishlist_amazon_id(value)
            if not value:
                raise forms.ValidationError("Doesn't look like a valid Wish List ID")

        if not WISHLIST_ID_REGEX.match(value):
            raise forms.ValidationError("Doesn't look like a valid Wish List ID")

        return value


class PaymentForm(BaseForm):
    uri = forms.CharField()
    amount = forms.CharField()
    hash = forms.CharField(required=False)
    uri = forms.CharField()
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        self.item = kwargs.pop('item')
        super(PaymentForm, self).__init__(*args, **kwargs)

    def clean_amount(self):
        value = self.cleaned_data['amount']
        value = str(value).replace('$', '').strip()
        try:
            value = decimal.Decimal(value)
        except decimal.InvalidOperation as x:
            raise forms.ValidationError(str(x))
        if value < 0.5:
            raise forms.ValidationError('Minimum is $0.50')
        left = self.item.amount_remaining
        if value > left:
            raise forms.ValidationError('Too much. Only $%.2f left to contribute.' % left)
        return value


class YourNameForm(BaseForm):
    your_email = forms.EmailField()
    your_name = forms.CharField()


class TakenForm(BaseForm):
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        self.wishlist = kwargs.pop('wishlist')
        super(TakenForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        value = self.cleaned_data['email']
        if value.lower().strip() != self.wishlist.email.lower().strip():
            raise forms.ValidationError('Not the same email address')
        return value


class WishlistAdminForm(BaseModelForm):

    class Meta:
        model = models.Wishlist
        fields = ('name', 'public', 'unsubscribe_reminders')


class ShareByEmailForm(BaseForm):

    emails = forms.CharField()
    send_copy = forms.BooleanField(required=False)

    def clean_emails(self):
        value = self.cleaned_data['emails']
        value = value.replace('\n', ',').replace(';', ',')
        #print "INPUT"
        #print repr(value)
        emails = address.parse_list(value)
        #print "OUTPUT"
        #print emails
        return emails


class FindWishlistForm(BaseForm):

    email = forms.CharField()

    def clean_email(self):
        value = self.cleaned_data['email']
        email = address.parse(value)
        if not email:
            raise forms.ValidationError("Not a valid email address")
        email = unicode(email)
        for w in models.Wishlist.objects.filter(email__iexact=email):
            return w.email
        raise forms.ValidationError("No Wish List set up with that address")


class CloseItemForm(BaseModelForm):

    class Meta:
        model = models.Item
        fields = ('closed', 'closed_notes')

webapp/main/templates/main/_instructions_shipping.email.html
{% extends "main/email_base.html" %}
{% block document_title %}{{ subject }}{% endblock %}

{% block extra_css %}
p.the-url { text-align: center }
p.the-url a { font-size: 120%; font-weight: bold; }
{% endblock %}

{% block content %}
  <h2>{{ subject }}</h2>
  <p>Congratulation on your
  <a href="{{ base_url }}{% url 'main:wishlist' item.identifier %}">{{ item.title }}</a>
  having been fully completed.</p>

  <p>To be able to now ship this to you, you now need to select an address
  that it can be shipped to.</p>

  <p>The instructions can be found here:</p>

  <p><a style="font-weight: bold"
    href="{{ base_url }}{% url 'main:instructions_shipping_address' %}">{{ base_url }}{% url 'main:instructions_shipping_address' %}</a></p>

  <p>{{ PROJECT_TITLE }} will later check that your Wish List, on amazon.com, has an address and
  ship your item to that address.</p>

{% endblock %}

webapp/main/templates/main/_nav.html
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <h3 class="text-muted">
      <a href="/" title="Home page of {{ PROJECT_TITLE }}"><img src="{{ STATIC_URL }}icons/icon-48.png" alt="Logo"></a>
      <a href="/" title="Home page of {{ PROJECT_TITLE }}">{{ PROJECT_TITLE }}</a>
    </h3>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    {% block header_nav %}
    <ul class="nav navbar-nav navbar-right">
      {% if your_wishlist %}
      <li><a href="{% url 'main:wishlist_settings' your_wishlist.identifier %}" title="Administer your Wish List"><i class="glyphicon glyphicon-cog"></i> Settings</a></li>
      {% endif %}
      <li><a href="{% url 'main:help' %}">Help</a></li>
      <li><a href="{% url 'main:how_it_works' %}">How It Works</a></li>
    </ul>
    {% endblock %}
  </div><!-- /.navbar-collapse -->
</nav>

webapp/main/templates/main/_notification.html
{% extends "main/email_base.html" %}
{% block document_title %}{{ subject }}{% endblock %}

{% block content %}
  <h3>Good News!</h3>
  <p class="lead">A contribution of <strong class="price">${{ payment.amount|floatformat:2 }}</strong>
  has been made towards your Wish List item <a href="{{ base_url }}{{ url }}"><strong>{{ item.title }}</strong></a>.</p>
  {% if payment.name %}
    <p>The contribution was made by <strong>{{ payment.name }}</strong>.</p>
    {% if payment.message %}
      <p>{{ payment.name }} left the following message:</p>
      <blockquote>{{ payment.message }}</blockquote>
    {% endif %}
  {% else %}
    {% if payment.message %}
      <p>The contribution was made by an <strong>anonymous friend</strong> who left the following message:</p>
      <blockquote>{{ payment.message }}</blockquote>
    {% else %}
      <p>The contribution was made by an <strong>anonymous friend</strong> who chose to not leave a message.</p>
    {% endif %}
  {% endif %}

{% if progress_complete %}
  <h3>Congratulations! The full amount has now been met. Your wish is now granted!</h3>
  <p class="lead">Your item will now be shipped to you.</p>
{% else %}
<table>
<tr>
<td><strong>Item price:</strong></td>
<td><span class="price">${{ item.price|floatformat:2 }}</span></td>
</tr>
<tr>
<td><strong>Total contributed:</strong></td>
<td><span class="price">${{ progress_amount|floatformat:2 }}</span></td>
</tr>
<tr>
<td><strong>Total remaining:</strong></td>
<td><span class="price">${{ amount_left|floatformat:2 }}</span></td>
</tr>
</table>
{% endif %}

<p>Revisit your Wish List here: <a href="{{ base_url }}{{ url }}">{{ base_url }}{{ url }}</a></p>

{% endblock %}

webapp/main/templates/main/_pay_form.html
        <form id="pay" class="form-horizontal pay" method="post" role="form">{% csrf_token %}
          {% if your_contributions %}
          <h4>Make Another Contribution</h4>
          {% else %}
          <h3>Make a Contribution</h3>
          {% endif %}
          <div class="other-error has-error">
            <h4>Some other error occurred</h4>
            <p>Your payment could not be processed at this time.</p>
            <p>Please try again a little later.</p>
          </div>
          <div class="form-group">

            <label for="id_amount" class="col-lg-4 control-label">Amount:</label>
            <div class="col-lg-6">
              <div class="input-group">
                <span class="input-group-addon">$</span>
                <input type="text" id="id_amount" name="amount" class="form-control" placeholder="e.g. $15"
              {% if amount_remaining %}value="{{ amount_remaining|floatformat:2 }}"{% endif %}>
              </div>

              <!--
              <input type="text" id="id_amount" name="amount" class="form-control" placeholder="e.g. $15"
              {% if amount_remaining %}value="{{ amount_remaining|floatformat:2 }}"{% endif %}>
              -->
              + {{ PAYMENT_TRANSACTION_PERCENTAGE }}% + ${{ PAYMENT_TRANSACTION_AMOUNT|floatformat:2 }} transaction fee [<a data-toggle="modal" href="#transaction-fee">tell me more</a>]
              <span class="help-block"></span>
            </div>
          </div>
          <div class="form-group credit-card" style="display:none">

            <div class="form-group">
              <label for="id_email" class="col-lg-4 control-label">Your Email:</label>
              <div class="col-lg-6">
                <input type="text" id="id_email" name="email" class="form-control" placeholder="your@email.com"
                 value="{% if email %}{{ email }}{% endif %}">
                <span class="help-block"><!--So you can get a receipt and if something happens with the payment--></span>
              </div>
            </div>

            <div class="form-group">
              <label for="id_card_number" class="col-lg-4 control-label">Card Number:</label>
              <div class="col-lg-6">
                <input type="text" id="id_card_number" name="card_number" class="form-control" placeholder="1234 1234 1234 1234"
                 data-android="{% if ANDROID %}true{% else %}false{% endif %}">
                <span class="help-block"></span>
              </div>
            </div>

            <div class="form-group">
              <label for="id_expiration_month" class="col-lg-4 control-label">Expiration Date (Month):</label>
              <div class="col-lg-2">
                <input type="text" id="id_expiration_month" name="expiration_month" class="form-control" placeholder="month">
                <span class="help-block"></span>
              </div>
            </div>

            <div class="form-group">
              <label for="id_expiration_year" class="col-lg-4 control-label">Expiration Date (Year):</label>
              <div class="col-lg-2">
                <input type="text" id="id_expiration_year" name="expiration_year" class="form-control" placeholder="year">
                <span class="help-block"></span>
              </div>
            </div>

            <div class="form-group">
              <label for="id_security_code" class="col-lg-4 control-label">Security Code (CSC):</label>
              <div class="col-lg-2">
                <input type="text" id="id_security_code" name="security_code" class="form-control" placeholder="123">
                <span class="help-block"></span>
              </div>
            </div>

            <!--
            <div class="form-group">
              <label for="id_postal_code" class="col-lg-4 control-label">Zip Code:</label>
              <div class="col-lg-2">
                <input type="text" id="id_postal_code" name="postal_code" class="form-control" placeholder="00000">
                <span class="help-block">xxx</span>
              </div>
            </div>
            -->

        {% if BALANCED_DEBUG %}
        <div class="form-error alert alert-info alert-dismissable">
          <p><b>Note!</b></p>
          <p>All payments are currently in <strong>TEST MODE</strong>.</p>
          <p>This message will go away when payments are for real.</p>
        </div>
        {% endif %}

          </div>
          <div class="form-group credit-card" style="display:none">
            <div class="col-lg-offset-2 col-lg-10">
              <button type="submit" class="btn btn-default btn-primary">Submit Your Contribution</button>
              <img src="{{ STATIC_URL }}main/images/spinner.gif" alt="Please wait" class="please-wait">
              <span class="please-wait">Please wait...</span>
            </div>
          </div>
          <div class="form-group credit-card" style="display:none">
	    <p>By submitting this form you agree to the
	    <a href="{% url 'main:terms' %}" class="terms-modal"
              data-toggle="modal" data-target="#terms">Terms of Use</a>.</p>
	  </div>

        </form>

webapp/main/templates/main/_share.email.html
{% extends "main/email_base.html" %}
{% block document_title %}{{ subject }}{% endblock %}

{% block extra_css %}
p.the-url { text-align: center }
p.the-url a { font-size: 130%; font-weight: bold; }
{% endblock %}


{% block content %}
<h3>Hi,</h3>
<p class="lead">I have set up a Wish List on <a href="{{ base_url }}">{{ PROJECT_TITLE }}</a>
and now I have kindly invited you to have a look in case you want to make a small contribution. Hint hint :)</p>

<p class="the-url">
<a href="{{ base_url }}{{ url }}">{{ base_url }}{{ url }}</a><br>
</p>

<p>
<b>From:</b>
{% if wishlist.name %}
{{ wishlist.name }}
{% endif %}
<a href="mailto:{{ wishlist.email }}">{{ wishlist.email }}</a>
</p>
{% endblock %}

webapp/main/templates/main/_verification_email_sent.html
<h3>Verification Email Sent</h3>

<h4>Ahhh... Now we're so close</h4>

<p>Please check your email (or spam filter) for an email sent from
<code>{{ WEBMASTER_FROM }}</code> sent to <b>{{ wishlist.email }}</b>
</p>

webapp/main/templates/main/wishlist_settings.html
{% extends "main/base.html" %}
{% load thumbnail %}
{% load bootstrap %}

{% block document_title %}Administer Your Wish List{% endblock %}

{% block extra_head %}
<style type="text/css">
.item {
    margin-bottom: 30px;
    padding-bottom: 10px;
    border-bottom: 1px solid #efefef;
}
.item img {
    float: right;
    margin-left: 10px;
    margin-bottom: 10px;
}
.another {
    margin: 60px;
    text-align: center;
}
.closed h4 {
    text-decoration: line-through;
}
</style>
{% endblock %}

{% block main %}

    {% if msg %}
    <div class="row marketing">
        <div class="alert alert-success alert-dismissable">
        <h4>{{ msg }}</h4>
        </div>
    </div>
    {% endif %}

    <div class="row marketing">
      <div class="col-lg-12">
        <h3>Administer Your Wish List</h3>
        <form action="." method="post">{% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>

    <div class="row marketing">
      <h3>You have the following Wish List Items set up</h3>

        {% for item, payments in items %}
        <div class="item clearfix {% if item.closed %}closed{% endif %}">
          {% if item.picture %}
            {% thumbnail item.picture "100x100" as thumb %}
            <a href="{% url 'main:wishlist' item.identifier %}"><img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ item.height }}" alt="{{ item.title }}"></a>
            {% endthumbnail %}
          {% else %}
            <a href="{% url 'main:wishlist' item.identifier %}"><img src="{{ STATIC_URL }}main/images/no-available-image-100x100.png" alt="No Image Available"></a>
          {% endif %}
          <h4><a href="{% url 'main:wishlist' item.identifier %}">{{ item.title }}</a></h4>
          <a href="{{ item.affiliates_url_or_url }}" target="_blank">On Amazon.com</a>
          <h4 class="price">${{ item.price|floatformat:2 }}</h4>
          <h4>Status:
            {% if item.fulfilled %}
              <i>Fulfilled!</i>
            {% else %}
              {% with progress_percent=item.progress_percent %}
              {% if progress_percent >= 100 %}
              <i>Complete!!</i> (expect an email from us shortly)
              {% else %}
                {% with payments_count=payments.count %}
                {% if payments_count %}
                  <i>{{ payments_count }} contribution{{ payments_count|pluralize }}
                  totalling <span class="price">{{ progress_percent }}%</span> of the total price
                  </i>
                  {% with amount_remaining=item.amount_remaining %}
                  <br>
                  <a href="{% url 'main:wishlist' item.identifier %}?amount={{ amount_remaining|floatformat:2 }}#pay">Pay the remaining
                  <span class="price">${{ amount_remaining|floatformat:2 }}</span> yourself</a>
                  {% endwith %}
                {% else %}
                  <i>No contributions made yet</i>
                {% endif %}
                {% endwith %}
              {% endif %}
              {% endwith %}
            {% endif %}
          </h4>

          {% if item.closed %}
          <p>This item is currently closed. <a href="{% url 'main:close_item' item.identifier %}">Re-open?</a></p>
          <p><em>{% if item.closed_noted %}{{ item.closed_notes }}{% else %}No notes.{% endif %}</em></p>
          {% else %}
            {% if not item.complete %}
            <p style="font-size:80%">
              Do you want to <a href="{% url 'main:close_item' item.identifier %}">Close this item</a>?
            </p>
            {% endif %}
          {% endif %}

          {% if item.fulfilled_notes %}
          <p>
            <b>Fulfillment Notes:</b><br>
            {{ item.fulfilled_notes }}
          </p>
          {% endif %}

        </div>
        {% endfor %}

    </div>

    <div class="row marketing another">
      <p>
        <a href="{% url 'main:wishlist_pick_another' wishlist.identifier %}" class="btn btn-primary">Set up another Wish List Item</a>
      </p>
    </div>

{% endblock %}